name: "Lint Markdown"

on:
  push:
    paths-ignore:
    - .*
    - README.md
    - LICENSE.md
    - CONTRIBUTING.md
    - Makefile
  pull_request:
    paths-ignore:
    - .*
    - README.md
    - LICENSE.md
    - CONTRIBUTING.md
    - Makefile

jobs:
  lint-changelog:
    name: Lint Markdown
    runs-on: ubuntu-latest
    steps:
    - name: Check out code
      uses: actions/checkout@v2
    - name: Run markdownlint
      uses: docker://avtodev/markdown-lint:v1
      with:
        args: 'draft-*.md'
